SELECT
  COURSES.Name,
  HOLES.Hole,
  HOLES.Par,
  HOLES.Distance
FROM
  COURSES
  JOIN HOLES ON COURSES.ID = HOLES.CourseID
  JOIN LAYOUTS ON HOLES.ID = LAYOUTS.HoleID
WHERE
  LAYOUTS.Layout = 1
ORDER BY
  LAYOUTS.Hole;